import os
import json

from notebook.base.handlers import APIHandler
from notebook.utils import url_path_join

from notebook.utils import maybe_future, url_path_join, url_unescape

import tornado
from tornado.web import StaticFileHandler
from swanprojects.config import get_software_stacks
import os
import shutil

from swanprojects.utils import project_path, get_project_info, get_project_readme

import subprocess

class ProjectInfoHandler(APIHandler):
    @tornado.web.authenticated
    def post(self):
        """
        Post request is for the SwanLauncher/SwanFileBrowser and returns project information required for the launcher 
        """
        # input_data is a dictionnary with a key "name"
        input_data = self.get_json_body()
        print("input_data = ",input_data)
        path = input_data["path"]
        project = project_path(path)
        self.kernel_spec_manager.set_path(path)
        project_data={}
        if project is not None:
            project_data = get_project_info(project)
            
            project_data["name"] = project.split(os.path.sep)[-1]
            readme = get_project_readme(project)
            if readme is not None:
                project_data["readme"] = readme
        payload = {"project_data":project_data}
        self.finish(json.dumps(payload))

class StacksInfoHandler(APIHandler):
    @tornado.web.authenticated
    def get(self):
        self.finish(json.dumps({"stacks": get_software_stacks()}))
        pass


class CreateProjectHandler(APIHandler):
    # The following decorator should be present on all verb methods (head, get, post,
    # patch, put, delete, options) to ensure only authorized user can request the
    # Jupyter server

    @tornado.web.authenticated
    def post(self):
        # input_data is a dictionnary with a key "name"
        input_data = self.get_json_body()
        print(input_data)
        name = input_data["name"]
        stack = input_data["stack"] ##CMSSW/LCG
        platform = input_data["platform"] #SCRAM
        release = input_data["release"] #CMSSW
        user_script = input_data["user_script"]

        project_dir=os.environ["HOME"]+"/SWAN_projects/"+name
        os.makedirs(project_dir)
        swan_project_file = project_dir+os.path.sep+'.swanproject'
        swan_project_content = {'stack':stack,'release':release,'platform':platform,'user_script':user_script}
        
        with open(swan_project_file,'w+') as f:
            f.write(json.dumps(swan_project_content, indent=4, sort_keys=True))
            f.close()
        
        command =  ["swan_kmspecs","--stack",stack,"--release",release,"--platform",platform,"--user_script",user_script,"--project_path",project_dir]
        print(" ".join(command))
        proc = subprocess.Popen(command, stdout = subprocess.PIPE)
        proc.wait()
        data = proc.stdout.read().decode("utf-8")
        print(data)
        proc.communicate()

        
        data = {"msg": "created project: {}".format(name)}
        self.finish(json.dumps(data))

class EditProjectHandler(APIHandler):
    # The following decorator should be present on all verb methods (head, get, post,
    # patch, put, delete, options) to ensure only authorized user can request the
    # Jupyter server

    @tornado.web.authenticated
    def post(self):
        # input_data is a dictionnary with a key "name"
        input_data = self.get_json_body()
        print(input_data)
        old_name = input_data["old_name"] 
        name = input_data["name"]
        stack = input_data["stack"] ##CMSSW/LCG
        platform = input_data["platform"] #SCRAM
        release = input_data["release"] #CMSSW
        user_script = input_data["user_script"]

        project_dir=os.environ["HOME"]+"/SWAN_projects/"+name
        if old_name !=name:
            old_project_dir=os.environ["HOME"]+"/SWAN_projects/"+old_name
            os.rename(old_project_dir,project_dir)

        swan_project_file = project_dir+os.path.sep+'.swanproject'
        swan_project_content = {'stack':stack,'release':release,'platform':platform,'user_script':user_script}
        kernel_dir = project_dir+"/.local/share/jupyter/kernels"

        #removing old native kernels for python only(this is generated by us)
        if os.path.exists(kernel_dir+"/python2"):
            shutil.rmtree(kernel_dir+"/python2")

        if os.path.exists(kernel_dir+"/python3"):
            shutil.rmtree(kernel_dir+"/python3")

        with open(swan_project_file,'w+') as f:
            f.write(json.dumps(swan_project_content, indent=4, sort_keys=True))
            f.close()
        
        command =  ["swan_kmspecs","--stack",stack,"--release",release,"--platform",platform,"--user_script",user_script,"--project_path",project_dir]
        print(" ".join(command))
        proc = subprocess.Popen(command, stdout = subprocess.PIPE)
        proc.wait()
        data = proc.stdout.read().decode("utf-8")
        print(data)
        proc.communicate()

        
        data = {"project_dir":"SWAN_projects/"+name,"msg": "project edited: {}".format(name)}
        self.finish(json.dumps(data))


# URL to handler mappings
def setup_handlers(web_app, url_path):
    host_pattern = ".*$"
    base_url = web_app.settings["base_url"]
    print("URL_PATH="+url_path)
    # Prepend the base_url so that it works in a jupyterhub setting
    create_pattern = url_path_join(base_url, url_path, "project/create")
    edit_pattern = url_path_join(base_url, url_path, "project/edit")
    project_pattern = url_path_join(base_url, url_path, "project/info")
    kernel_pattern = url_path_join(base_url, url_path, "stacks/info")
    #http://localhost:8888/api/kernelspecs
    handlers = [(create_pattern, CreateProjectHandler)]
    handlers.append((edit_pattern,EditProjectHandler))
    handlers.append((project_pattern,ProjectInfoHandler))
    handlers.append((kernel_pattern,StacksInfoHandler))

    web_app.add_handlers(host_pattern, handlers)

    # Prepend the base_url so that it works in a jupyterhub setting
    doc_url = url_path_join(base_url, url_path, "static")
    doc_dir = os.getenv(
        "JLAB_SERVER_EXAMPLE_STATIC_DIR",
        os.path.join(os.path.dirname(__file__), "static"),
    )
    handlers = [("{}/(.*)".format(doc_url), StaticFileHandler, {"path": doc_dir})]
    web_app.add_handlers(".*$", handlers)
